config/routes.rb
Rails.application.routes.draw do
  resources :meals
  root 'home#index'

  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meal.rb
class Meal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
 
  def about
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: %i[ show edit update destroy ]

  # GET /meals or /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1 or /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals or /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to meal_url(@meal), notice: "Meal was successfully created." }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1 or /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to meal_url(@meal), notice: "Meal was successfully updated." }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1 or /meals/1.json
  def destroy
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url, notice: "Meal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meal_params
      params.require(:meal).permit(:meal, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/home/_footer.html.erb
<hr>
<footer> now i'm the footer</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Dinner App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'List Meals', meals_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add a Meal', new_meal_path, class: 'nav-link' %>
        </li>
       
      </ul>
 
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>about page</h1>

app/views/home/index.html.erb
<h1>This is the home page for the whole app</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div class="container" style="display: flex;flex-direction: column;min-height: 100vh;">
    <%= render 'home/header' %>
    <div style=" flex-grow: 1" >  
      <%= yield %>
    </div>
    <%= render 'home/footer' %>

  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_with(model: meal) do |form|  %>
  <% if meal.errors.any? %>
    <div style="color: red" >
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
        <% meal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :meal, style: "display: block" %>
    <%= form.text_field :meal %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div class='mt-3'>
    <%= form.submit %>
  </div>
<% end %>

app/views/meals/_meal.html.erb
<div id="<%= dom_id meal %>">
  <p>
    <strong>Meal:</strong>
    <%= meal.meal %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= meal.date %>
  </p>

</div>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render "form", meal: @meal %>

<br>

<div>
  <%= link_to "Show this meal", @meal %> |
  <%= link_to "Back to meals", meals_path %>
</div>

app/views/meals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meals</h1>

<div id="meals" style='display:flex'>
  <% @meals.each do |meal| %>
    <div class="card m-2 p-2" ><%= render meal %>
    <p>
      <%= link_to "Show this meal", meal %>
    </p></div>
  <% end %>
</div>

<%= link_to "New meal", new_meal_path, class:"btn btn-primary m-2" %>

app/views/meals/new.html.erb
<h1>Add a New meal</h1>
<%= render "form", meal: @meal %>

<br>

<div>
  <%= link_to "Back to meals", meals_path %>
</div>

app/views/meals/show.html.erb
<p style="color: green"><%= notice %></p>
<div class='card p-2'>
<%= render @meal %>

<div >
  <%= link_to "Edit this meal", edit_meal_path(@meal), class:'btn btn-warning m-1' %> 

  <%= button_to "Destroy this meal", @meal, method: :delete , class:'btn btn-danger m-1' %>
  <%= link_to "Back to meals", meals_path, class:'btn btn-primary m-1'  %>
</div>
</div>